version: '3.5'
services:
  heartbeat:
    image: docker.elastic.co/beats/heartbeat:8.5.1
    container_name: heartbeat
    volumes: 
      - ./heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro
    command: heartbeat -e -strict.perms=false