apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server-1
  namespace: elastic-system
spec:
  version: 9.1.2
  count: 1
  elasticsearchRef:
    name: elasticsearch  # Replace with your actual Elasticsearch cluster name
    namespace: elastic-system
  config:
    ssl:
      verification_mode: "none"
    logging:
      level: debug
  podTemplate:
    spec:
      containers:
        - name: apm-server
          resources:
            requests:
              memory: 512Mi
              cpu: 0.25
            limits:
              memory: 1Gi
              cpu: 0.5