apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-server
  namespace: elastic-system
spec:
  version: 9.1.2  # Match your Elasticsearch/Kibana version
  elasticsearchRefs:
    - name: elasticsearch
  kibanaRef:
    name: kibana
  mode: fleet
  fleetServerEnabled: true
  policyID: fleet-server-policy
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
          - name: agent
            resources:
              requests:
                cpu: "200m"
                memory: "512Mi"
              limits:
                cpu: "1"
                memory: "1Gi"

---

kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: fleet-vs
  namespace: elastic-system
spec:
  gateways:
  - istio-system/cert-manager-gateway
  hosts:
  - fleet.zitaconseil.fr
  http:
  - route:
    - destination:
        host: fleet-server-agent-http.elastic-system.svc.cluster.local
        port:
          number: 8220

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: fleet-dr
  namespace: elastic-system
spec:
  host: fleet-server-agent-http.elastic-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 8220
        tls:
          mode: SIMPLE  # enables HTTPS
          insecureSkipVerify: true


---

kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  name: elasticsearch-vs
  namespace: elastic-system
spec:
  gateways:
  - istio-system/cert-manager-gateway
  hosts:
  - elastic.zitaconseil.fr
  http:
  - route:
    - destination:
        host: elasticsearch-es-http.elastic-system.svc.cluster.local
        port:
          number: 9200

---

apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: elasticsearch-dr
  namespace: elastic-system
spec:
  host: elasticsearch-es-http.elastic-system.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
      - port:
          number: 9200
        tls:
          mode: SIMPLE  # enables HTTPS
          insecureSkipVerify: true          