apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: fleet-agent
  namespace: elastic-system
spec:
  version: 9.1.2
  mode: fleet
  fleetServerEnabled: false
  policyRef:
    name: agent-policy
  fleetServerRef:
    name: fleet-server
    namespace: elastic-system
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
          - env:
            - name: FLEET_ENROLLMENT_TOKEN
              value: "SXNIX1Nab0JVb3ZvUnhyYlF0V046bWpOQUhnWFJfd2o3dmE0dFcwaWQydw=="
          - name: agent

            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "500m"
                memory: "512Mi"
