#kubectl apply -f https://raw.githubusercontent.com/elastic/cloud-on-k8s/3.1/config/recipes/beats/heartbeat_es_kb_health.yaml
apiVersion: beat.k8s.elastic.co/v1beta1
kind: Beat
metadata:
  name: heartbeat
spec:
  type: heartbeat
  version: 9.1.2
  elasticsearchRef:
    name: elasticsearch
  config:
    heartbeat.monitors:
    - type: tcp
      schedule: '@every 1m'
      hosts: ["elasticsearch-es-http.default.svc:9200"]
    - type: tcp
      schedule: '@every 1m'
      hosts: ["kibana-kb-http.default.svc:5601"]     
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0