
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: observability
spec:
  exporter:
    endpoint: http://otel-collector-collector.observability.svc.cluster.local:4318
  
  propagators:
    - tracecontext
    - baggage
    - b3
  
  sampler:
    type: parentbased_traceidratio
    argument: "1.0"

  nodejs:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      # - name: OTEL_EXPORTER_OTLP_ENDPOINT
      #   value: http://otel-collector:4318
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.observability.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: "Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=MINT"
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp  # ACTIVER les logs OTLP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_LOG_LEVEL
        value: INFO
      - name: OTEL_EXPORTER_OTLP_INSECURE
        value: "true"        

  python:
#    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:1.28.1
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.observability.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: "Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=MINT"
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp  # ACTIVER les logs OTLP
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf
      - name: OTEL_LOG_LEVEL
        value: INFO
      - name: OTEL_EXPORTER_OTLP_INSECURE
        value: "true"  

  java:
    #image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:2.17.0
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.observability.svc.cluster.local:4318
      - name: OTEL_EXPORTER_OTLP_HEADERS
        value: "Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO"
      - name: OTEL_RESOURCE_ATTRIBUTES
        value: "deployment.environment=MINT"
      # - name: OTEL_SERVICE_NAME
      #   valueFrom:
      #     fieldRef:
      #       fieldPath: metadata.labels['app.kubernetes.io/version']
      - name: OTEL_TRACES_EXPORTER
        value: otlp
      - name: OTEL_METRICS_EXPORTER
        value: otlp
      - name: OTEL_LOGS_EXPORTER
        value: otlp  # ACTIVER les logs OTLP
      # - name: OTEL_EXPORTER_OTLP_PROTOCOL
      #   value: grpc
      - name: OTEL_EXPORTER_OTLP_PROTOCOL
        value: http/protobuf

      - name: OTEL_LOG_LEVEL
        value: INFO
      - name: OTEL_EXPORTER_OTLP_INSECURE
        value: "true"        
      # Configuration des logs
      - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED
        value: "true"  # ACTIVER l'appender Logback
      - name: OTEL_INSTRUMENTATION_LOGBACK_MDC_ADD_BAGGAGE
        value: "true"
      
      # Autres instrumentations
      - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_ENABLED
        value: "true"
      - name: OTEL_INSTRUMENTATION_SPRING_BOOT_ENABLED
        value: "true"