apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: observability
spec:
  mode: daemonset
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15
      batch:
        send_batch_size: 100
        timeout: 5s

    exporters:
      # NOTE: Prior to v0.86.0 use `logging` instead of `debug`.
      debug:
        verbosity: detailed
      otlp/apm:
        endpoint: "http://apm-server-apm-http.elastic-system.svc.cluster.local:8200"
        tls:
          insecure: true
        headers:
          Authorization: "Bearer KA9Q7p471Wx0S49kSP81RoyO"
      otlp/jaeger:
        endpoint: "http://jaeger-collector.istio-system.svc.cluster.local:4317"
        tls:
          insecure: true
      prometheus:
        endpoint: "0.0.0.0:9464"   # Prometheus exporter port

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp/apm, otlp/jaeger] 
        metrics:
          receivers: [otlp]
          processors: [memory_limiter, batch]
          exporters: [debug, otlp/apm, prometheus]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [debug, otlp/apm]
