apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  annotations:
    instrumentation.opentelemetry.io/default-auto-instrumentation-apache-httpd-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    instrumentation.opentelemetry.io/default-auto-instrumentation-dotnet-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-go-image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.22.1
    instrumentation.opentelemetry.io/default-auto-instrumentation-java-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.33.6
    instrumentation.opentelemetry.io/default-auto-instrumentation-nginx-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    instrumentation.opentelemetry.io/default-auto-instrumentation-nodejs-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.62.0
    instrumentation.opentelemetry.io/default-auto-instrumentation-python-image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.57b0
  name: otel-instrumentation
  namespace: observability
spec:
  apacheHttpd:
    configPath: /usr/local/apache2/conf
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 128Mi
    version: "2.4"
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  defaults: {}
  dotnet:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-dotnet:1.2.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  exporter:
    endpoint: http://otel-collector-collector.observability.svc.cluster.local:4318
  go:
    image: ghcr.io/open-telemetry/opentelemetry-go-instrumentation/autoinstrumentation-go:v0.22.1
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  java:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-collector.observability.svc.cluster.local:4318
    # - name: OTEL_EXPORTER_OTLP_HEADERS
    #   value: Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: "deployment.environment=MINT"
      
    - name: OTEL_INSTRUMENTATION_LOG4J-APPENDER_ENABLED
      value: "true"
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_LOG_LEVEL
      value: debug
    - name: OTEL_JAVAAGENT_DEBUG
      value: "false"      
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_INSTRUMENTATION_LOGBACK_APPENDER_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_LOGBACK_MDC_ADD_BAGGAGE
      value: "true"
    - name: OTEL_INSTRUMENTATION_SPRING_WEBMVC_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_JDBC_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_HTTP_CLIENT_ENABLED
      value: "true"
    - name: OTEL_INSTRUMENTATION_SPRING_BOOT_ENABLED
      value: "true"
    # - name: OTEL_PROPAGATORS
    #   value: tracecontext,baggage,b3multi,b3
    - name: OTEL_TRACES_SAMPLER
      value: always_on
    # - name: OTEL_TRACES_SAMPLER_ARG
    #   value: "1.0"
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-java:1.33.6
    resources:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  nginx:
    configFile: /etc/nginx/nginx.conf
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 1m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  nodejs:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-collector.observability.svc.cluster.local:4318
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=MINT
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_LOG_LEVEL
      value: DEBUG
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"
    - name: OTEL_TRACES_SAMPLER
      value: always_on

    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-nodejs:0.62.0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  propagators:
  - tracecontext
  - baggage
  - b3
  python:
    env:
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: http://otel-collector-collector.observability.svc.cluster.local:4318
    - name: OTEL_EXPORTER_OTLP_HEADERS
      value: Authorization=Bearer KA9Q7p471Wx0S49kSP81RoyO
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: deployment.environment=MINT
    - name: OTEL_TRACES_EXPORTER
      value: otlp
    - name: OTEL_METRICS_EXPORTER
      value: otlp
    - name: OTEL_LOGS_EXPORTER
      value: otlp
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: http/protobuf
    - name: OTEL_LOG_LEVEL
      value: INFO
    - name: OTEL_EXPORTER_OTLP_INSECURE
      value: "true"

    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:0.57b0
    resourceRequirements:
      limits:
        cpu: 500m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 64Mi
    volumeClaimTemplate:
      metadata: {}
      spec:
        resources: {}
  resource: {}
  sampler:
    argument: "1.0"
    type: parentbased_traceidratio
